name: 02 Build AMIs with Packer

on:
  # push:
  #   branches: [ "main" ]  
  workflow_dispatch:
  
env:
  AWS_REGION: ${{ vars.AWS_REGION }}

permissions:
  contents: read

jobs:
  packer:
    name: 'Build AMI with Packer'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Prepare certs and config files
      run: export PATH=/tmp/kthw-certs:$PATH; for i in $(ls ./scripts-for-certs-and-configs/); do bash ./scripts-for-certs-and-configs/$i; done

    - name: Packer Init
      run: packer init ./packer/

    - name: Packer Build
      run: packer build ./packer/08-load-balancer-internal.pkr.hcl