name: 03 Deploying EC2 on AWS

on:
  workflow_dispatch:
  
env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  TERRAFORM_PATH: "./terraform/"
  
permissions:
  contents: read

jobs:
  terraform:
    name: 'Deploy EC2 on AWS'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Replace Region in Provider section of Terraform  
      run: sed -i 's/us-east-1/$AWS_REGION/g' $TERRAFORM_PATH/00-provider.tf

    - name: Terraform Init
      run: terraform -chdir=$TERRAFORM_PATH init

    - name: Terraform Plan
      run: terraform -chdir=$TERRAFORM_PATH plan -input=false -var "aws_region=$AWS_REGION"
      
    - name: Terraform Apply
      run: terraform -chdir=$TERRAFORM_PATH apply -auto-approve -input=false -var "aws_region=$AWS_REGION"
